require_relative './project1/version'
require 'nokogiri'
require 'pry'
require 'open-uri'
require 'tty-table'
require 'colorize'

require_relative './project1/cli'
require_relative './project1/fund'
require_relative './project1/version'
require_relative './project1/category'
require_relative './project1/scraper'